name: my_wallet
description: "An application that helps you manage your income and expenses"
publish_to: 'none'
version: 1.0.2+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  # pub base
  dio: ^5.4.0
  rxdart: ^0.27.7
  intl: ^0.18.1
  flutter_localizations:
    sdk: flutter
  equatable: ^2.0.5
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.0
  loading_indicator: ^3.1.1
  # pub other
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_bloc: ^8.1.3
  firebase_core: ^2.30.1
#  google_mobile_ads: ^5.0.0
  fl_chart: ^0.67.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  # pub base: flutter pub run build_runner build
  build_runner: ^2.4.7
  hive_generator: ^2.0.1
  # pub other
  icons_launcher: ^2.1.7

flutter_intl:
  enabled: true

flutter:

  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/icons/
    - assets/images/
    - assets/config/

  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Bold.ttf
        - asset: assets/fonts/OpenSans-BoldItalic.ttf
        - asset: assets/fonts/OpenSans-ExtraBold.ttf
        - asset: assets/fonts/OpenSans-ExtraBoldItalic.ttf
        - asset: assets/fonts/OpenSans-Italic.ttf
        - asset: assets/fonts/OpenSans-Light.ttf
        - asset: assets/fonts/OpenSans-LightItalic.ttf
        - asset: assets/fonts/OpenSans-Medium.ttf
        - asset: assets/fonts/OpenSans-MediumItalic.ttf
        - asset: assets/fonts/OpenSans-Regular.ttf
        - asset: assets/fonts/OpenSans-SemiBold.ttf
        - asset: assets/fonts/OpenSans-SemiBoldItalic.ttf
