name: base_flutter
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  # pub base
  dio: ^5.4.0
  rxdart: ^0.27.7
  intl: ^0.18.1
  flutter_localizations:
    sdk: flutter
  # pub other

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter_intl:
  enabled: true

flutter:

  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/icons/
    - assets/images/

  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/font/OpenSans-Bold.ttf
        - asset: assets/font/OpenSans-BoldItalic.ttf
        - asset: assets/font/OpenSans-ExtraBold.ttf
        - asset: assets/font/OpenSans-ExtraBoldItalic.ttf
        - asset: assets/font/OpenSans-Italic.ttf
        - asset: assets/font/OpenSans-Light.ttf
        - asset: assets/font/OpenSans-LightItalic.ttf
        - asset: assets/font/OpenSans-Medium.ttf
        - asset: assets/font/OpenSans-MediumItalic.ttf
        - asset: assets/font/OpenSans-Regular.ttf
        - asset: assets/font/OpenSans-SemiBold.ttf
        - asset: assets/font/OpenSans-SemiBoldItalic.ttf
